version: '3.8'

services:
  db:
    container_name: "valley-of-positivity-baza"
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ValleyOfPositivity
      MYSQL_USER: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    container_name: "valley-of-positivity-phpmyadmin"
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""  # No password since you're allowing empty password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: