version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ValleyOfPositivity
      MYSQL_USER: root
    ports:
      - "3307:3306"  # Change this line
    volumes:
      - db_data:/var/lib/mysql
  
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5240:80"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

volumes:
  db_data:
