services:
  # Backend service configuration
  - type: web
    name: my-dotnet-backend
    env: docker  # Specify that this service uses Docker
    repo: https://github.com/ebronja1/Valley-of-Positivity/api
    branch: main
    dockerfilePath: ./Dockerfile # Path to your Dockerfile for .NET backend
    buildCommand: ""  # Optional, can be removed if not needed
    startCommand: "dotnet ValleyOfPositivity.dll"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        value: mysql://root:@my-mysql-database:3306/ValleyOfPositivity
    healthCheckPath: "/health"
    autoDeploy: true
    plan: free

  # Frontend service configuration
  - type: web
    name: my-react-frontend
    env: static  # Specify that this service is a static site
    repo: https://github.com/ebronja1/Valley-of-Positivity/frontend
    branch: main
    buildCommand: "npm install && npm run build"
    publishPath: build  # Correct the publish path to match your build output
    envVars:
      - key: REACT_APP_API_URL
        value: "https://valley-of-positivity.onrender.com"
    autoDeploy: true
    plan: free

  # MySQL Database configuration (self-hosted)
  - type: web
    name: my-mysql-database
    env: docker
    image: mysql:8.0  # Use MySQL Docker image
    startCommand: ""
    envVars:
      - key: MYSQL_ALLOW_EMPTY_PASSWORD
        value: "yes"
      - key: MYSQL_DATABASE
        value: ValleyOfPositivity
      - key: MYSQL_USER
        value: root
    plan: free
    disk:
      sizeGB: 5  # Set disk size for data persistence






