services:
  # Backend service configuration
  - type: web
    name: my-dotnet-backend
    env: docker  # Specify that this service uses Docker
    repo: https://github.com/ebronja1/Valley-of-Positivity/api
    branch: main
    dockerfilePath: ./Dockerfile # Path to your Dockerfile for .NET backend
    buildCommand: ""  # Optional, can be removed if not needed
    startCommand: "dotnet ValleyOfPositivity.dll"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        value: "mysql://freedb_student030598:SQZafsZg9@N#k4A@sql.freedb.tech:3306/freedb_ValleyOfPositivity"
    healthCheckPath: "/health"
    autoDeploy: true
    plan: free

  # Frontend service configuration
  - type: web
    name: my-react-frontend
    env: static  # Specify that this service is a static site
    repo: https://github.com/ebronja1/Valley-of-Positivity/frontend
    branch: main
    buildCommand: "npm install && npm run build"  # Builds the frontend
    envVars:
      - key: REACT_APP_API_URL
        value: "https://my-dotnet-backend.onrender.com"  # Update if necessary
    autoDeploy: true
    plan: free









