services:
  # Backend service configuration
  - type: web
    name: my-dotnet-backend
    env: docker  # Specify that this service uses Docker
    repo: https://github.com/ebronja1/Valley-of-Positivity/api
    branch: main
    dockerfilePath: ./Dockerfile # Path to your Dockerfile for .NET backend
    buildCommand: ""  # Optional, can be removed if not needed
    startCommand: "dotnet ValleyOfPositivity.dll"
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        value: postgres://your_db_user:your_db_password@my-postgres-database:5432/ValleyOfPositivity  # Update with your DB credentials
    healthCheckPath: "/health"
    autoDeploy: true
    plan: free

  # Frontend service configuration
  - type: web
    name: my-react-frontend
    env: static  # Specify that this service is a static site
    repo: https://github.com/ebronja1/Valley-of-Positivity/frontend
    branch: main
    buildCommand: "npm install && npm run build"  # Builds the frontend
    envVars:
      - key: REACT_APP_API_URL
        value: "https://my-dotnet-backend.onrender.com"  # Update if necessary
    autoDeploy: true
    plan: free

  # PostgreSQL Database configuration
  - type: postgres  # Using managed PostgreSQL
    name: my-postgres-database
    databaseName: ValleyOfPositivity
    user: your_db_user  # Update with your desired username
    password: your_db_password  # Update with your desired password
    plan: free
    region: oregon  # Update to your preferred region







